name: Terraform validation

on:
  push:
  pull_request:

jobs:
  terraform-validate:
    name: Terraform formatting and validation check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize terraform
        run: terraform init

      - name: Check formatting
        run: terraform fmt -check -recursive
        
      - name: Validate terraform
        run: terraform validate