name: Terraform validation

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform formatting and validation check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform fmt -check -recursive
      - run: terraform validate